### ISSUE TITLE
Base de datos

### ISSUE THREAD

**Issue by jpcrespo** [CobraPython/BitcoinResearch#5]
Para que puedas evaluar análisis sin esperar cada respuesta del core, pensaba que podemos hacer un bot que transforme los datos de los bloques en otro formato y te lo mande.

Podría transformarse a varias cosas:

Un texto plano csv, una planilla de excel, un array en npy, una bd como sql, entre otros.

¿Qué crees que sería mejor? 
Yo diría a sql solo por aprender/practicar con python.

**Comment by jpcrespo** [comment]
? @CarlosCCC9

**Comment by CarlosCCC9** [comment]
Podriamos probar con la interfaz de mysql para python, es algo que ya conozco y me dio buenos resultados

**Comment by CarlosCCC9** [comment]
Disculpa, me llego la notificacion del segundo mensaje unicamente

**Comment by CarlosCCC9** [comment]
esta noche subire un ejemplo de mysql

**Comment by jpcrespo** [comment]
dale, ya funca los métodos para jalar info del bitcoin-core desde otros puntos del nodo.
Seria cool q armes un minicursito y pongamos unos ejemplos para armar un script q saque la info desde el bloque 1 y la guardamos en nuestra base de datos.

Seria un bot q cada 10 min traduzca a sqp

**Comment by CarlosCCC9** [comment]
Suena interesante,  voy a empezar a diseñarlo
