### ISSUE TITLE
Multiples errores

### ISSUE THREAD

**Issue by CarlosCCC9** [CobraPython/BitcoinResearch#8]
Pues, olvide el nombre de mi host, user y pass.
Hice todo de nuevo, pero ahora:
- primero me salio name or service not known
- cambie el user y me salio la autenticidad no puede ser establecida, continuar la conexion? le di si, me pide password pero no funciona con la que puse
- y ya no se reconoce a mi tera hdd, en ninguna de mis maquinas

**Comment by CarlosCCC9** [comment]
![Captura desde 2022-11-30 21-01-22](https://user-images.githubusercontent.com/71854944/204940818-8a60fcc4-dae2-4972-a3f6-044f5c7bd5b5.png)

**Comment by jpcrespo** [comment]
Me parece que se corrompió al quemar la imagen usb. Muy raro nunca lo había visto. 

y ya no se reconoce a mi tera hdd, en ninguna de mis maquinas

**Comment by jpcrespo** [comment]
y ya no se reconoce a mi tera hdd, en ninguna de mis maquinas:
Esto esta mas loco todavía, no se daño el disco rígido? te lo reconoce en otra pc con win?

hay algunas herramientas para checar si lo reconoce, lo vemos a la noche.
